### ISSUE TITLE
In the tutorial settings, clients that support the meta kernel cannot import subscriptions with one click

### ISSUE THREAD

**Issue by peter2186668355** [xcode75/XManagerPlus#352]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

In the tutorial settings, clients that support the meta kernel cannot import subscriptions with one click

### Reproduction Method

In the tutorial settings, clients that support the meta kernel cannot import subscriptions with one click，

### Panel Version

<details><pre><code>

</code></pre></details>

### PHP version

<details><pre><code>

</code></pre></details>

### Panel config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Panel Error log

<details><pre><code>

</code></pre></details>

### Server Error log

<details><pre><code>

</code></pre></details>

### App or Client type(version)

<details><pre><code>

</code></pre></details>

**Comment by peter2186668355** [comment]
请尽快解决
